version: '3.8'

services:

  motor-simulacao:
    build:
      context: ./motor-simulacao
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - internal-network
    depends_on:
      - mysql
      - mongodb
    environment:
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: simlador_credito
      MONGO_URI: mongodb://root:rootpassword@mongodb:27017/simlador_credito?authSource=admin
    command: ["./wait-for-it.sh", "mysql:3306", "--", "./wait-for-it.sh", "mongodb:27017", "--", "go", "run", "cmd/main.go"]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: simlador_credito
    volumes:
      - $PWD/infra/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - internal-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: simlador_credito
    ports:
      - "27017:27017"
    networks:
      - internal-network
    volumes:
      - $PWD/infra/mongodb/init.js:/docker-entrypoint-initdb.d/init.js

networks:
  internal-network:
    driver: bridge