// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package rest

// GeneralErrorResponse defines model for GeneralErrorResponse.
type GeneralErrorResponse struct {
	// Code Códigos de erro para identificação de problemas
	Code *string `json:"code,omitempty"`

	// Message Mensagem de erro detalhada
	Message *string `json:"message,omitempty"`
}

// SimulationRequest defines model for SimulationRequest.
type SimulationRequest struct {
	// Age Idade do solicitante
	Age int `json:"age"`

	// Amount Valor do crédito solicitado
	Amount float64 `json:"amount"`

	// Installments Número de parcelas para pagamento
	Installments int `json:"installments"`
}

// CreateSimulationJSONRequestBody defines body for CreateSimulation for application/json ContentType.
type CreateSimulationJSONRequestBody = SimulationRequest
